-- -------------------------------------------------------------
--
-- Generated Architecture Declaration for struct of di_tnr
--
-- Generated
--  by:  lutscher
--  on:  Tue Jun 23 14:19:39 2009
--  cmd: /home/lutscher/work/MIX/mix_1.pl di_tnr.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Architecture Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
--
-- Generator: mix_1.pl Revision: 1.3 , wilfried.gaensheimer@micronas.com
-- (C) 2003,2005 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/arch


--
--
-- Start of Generated Architecture struct of di_tnr
--
architecture struct of di_tnr is 

	--
	-- Generated Constant Declarations
	--


	--
	-- Generated Components
	--
	component di_tnr_ctrl
		-- No Generated Generics
		port (
		-- Generated Port for Entity di_tnr_ctrl
			af_c0_o	: out	std_ulogic ;
			af_c1_o	: out	std_ulogic;
			af_p0_i	: in	std_ulogic;
			al_c0_o	: out	std_ulogic;
			al_c1_o	: out	std_ulogic;
			al_c2_o	: out	std_ulogic;
			al_p0_i	: in	std_ulogic;
			ap_c0_o	: out	std_ulogic;
			ap_c1_o	: out	std_ulogic;
			ap_p0_i	: in	std_ulogic;
			asresi_n	: in	std_ulogic;
			clkin	: in	std_ulogic;
			field_p0_i	: in	std_ulogic;
			fieldc_c1_o	: out	std_ulogic;
			fieldy0_c1_o	: out	std_ulogic;
			fieldy1_c1_o	: out	std_ulogic;
			frafiesel_iic_i	: in	std_ulogic;
			hsync_c1_o	: out	std_ulogic;
			hsync_p0_i	: in	std_ulogic;
			hsync_p0_o	: out	std_ulogic;
			req_p1_o	: out	std_ulogic;
			tnrmdnr4c_iic_i	: in	std_ulogic;
			tnrnr4y_iic_i	: in	std_ulogic;
			uen_c1_o	: out	std_ulogic;
			uen_p0_i	: in	std_ulogic;
			vsync_c1_o	: out	std_ulogic;
			vsync_p0_i	: in	std_ulogic
		-- End of Generated Port for Entity di_tnr_ctrl
		);
	end component;
	-- ---------

	component di_tnrc
		-- No Generated Generics
		port (
		-- Generated Port for Entity di_tnrc
			af_c0_i	: in	std_ulogic ;
			al_c0_i	: in	std_ulogic;
			al_c1_i	: in	std_ulogic;
			ap_c0_i	: in	std_ulogic;
			ap_p0_i	: in	std_ulogic;
			asresi_n	: in	std_ulogic;
			c_p0_i	: in	std_ulogic_vector(7 downto 0);
			c_p0_o	: out	std_ulogic_vector(7 downto 0);
			c_p1_i	: in	std_ulogic_vector(7 downto 0);
			c_p1_o	: out	std_ulogic_vector(7 downto 0);
			cblack_p_i	: in	std_ulogic_vector(7 downto 0);
			clkin	: in	std_ulogic;
			hsync_c_i	: in	std_ulogic;
			nr_dis_c_i	: in	std_ulogic;
			nron_iic_i	: in	std_ulogic;
			tnrabs_iic_i	: in	std_ulogic;
			tnrclc_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrkvaly_p_i	: in	std_ulogic_vector(3 downto 0);
			tnrs0c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs1c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs2c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs3c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs4c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs5c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs6c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs7c_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrsel_iic_i	: in	std_ulogic;
			tnrssc_iic_i	: in	std_ulogic_vector(3 downto 0)
		-- End of Generated Port for Entity di_tnrc
		);
	end component;
	-- ---------

	component di_tnry
		-- No Generated Generics
		port (
		-- Generated Port for Entity di_tnry
			af_c0_i	: in	std_ulogic ;
			al_c0_i	: in	std_ulogic;
			al_c1_i	: in	std_ulogic;
			ap_c0_i	: in	std_ulogic;
			ap_p0_i	: in	std_ulogic;
			asresi_n	: in	std_ulogic;
			clkin	: in	std_ulogic;
			hsync_c_i	: in	std_ulogic;
			nr_dis_c_i	: in	std_ulogic;
			nron_iic_i	: in	std_ulogic;
			tnrabs_iic_i	: in	std_ulogic;
			tnrcly_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrkvaly_p_o	: out	std_ulogic_vector(3 downto 0);
			tnrmd4y_iic_i	: in	std_ulogic;
			tnrnr4y_iic_i	: in	std_ulogic;
			tnrs0y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs1y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs2y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs3y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs4y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs5y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs6y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrs7y_iic_i	: in	std_ulogic_vector(3 downto 0);
			tnrssy_iic_i	: in	std_ulogic_vector(3 downto 0);
			y0_p1_i	: in	std_ulogic_vector(7 downto 0);
			y0_p1_o	: out	std_ulogic_vector(7 downto 0);
			y1_p1_i	: in	std_ulogic_vector(7 downto 0);
			y1_p1_o	: out	std_ulogic_vector(7 downto 0);
			y_p0_i	: in	std_ulogic_vector(7 downto 0);
			y_p0_o	: out	std_ulogic_vector(7 downto 0);
			yblack_p_i	: in	std_ulogic_vector(7 downto 0)
		-- End of Generated Port for Entity di_tnry
		);
	end component;
	-- ---------



	--
	-- Generated Signal List
	--
		signal	af_c0	: std_ulogic ; 
		signal	al_c0	: std_ulogic; 
		signal	al_c2	: std_ulogic; 
		signal	ap_c0	: std_ulogic; 
		signal	hsync_c	: std_ulogic; 
		signal	tnrkvaly	: std_ulogic_vector(3 downto 0); 
	--
	-- End of Generated Signal List
	--




begin


	--
	-- Generated Concurrent Statements
	--

	--
	-- Generated Signal Assignments
	--


	--
	-- Generated Instances and Port Mappings
	--
		-- Generated Instance Port Map for ctrl
		ctrl: di_tnr_ctrl
		port map (

			af_c0_o => af_c0,
			af_c1_o => af_c1_o,
			af_p0_i => af_p0_i,
			al_c0_o => al_c0,
			al_c1_o => al_c1_o,
			al_c2_o => al_c2,
			al_p0_i => al_p0_i,
			ap_c0_o => ap_c0,
			ap_c1_o => ap_c1_o,
			ap_p0_i => ap_p0_i,
			asresi_n => asresi_n,
			clkin => clkin,
			field_p0_i => field_p0_i,
			fieldc_c1_o => fieldc_c1_o,
			fieldy0_c1_o => fieldy0_c1_o,
			fieldy1_c1_o => fieldy1_c1_o,
			frafiesel_iic_i => frafiesel_iic_i,
			hsync_c1_o => hsync_c1_o,
			hsync_p0_i => hsync_p0_i,
			hsync_p0_o => hsync_c,
			req_p1_o => req_p1_o,
			tnrmdnr4c_iic_i => tnrmdnr4c_iic_i,
			tnrnr4y_iic_i => tnrnr4y_iic_i,
			uen_c1_o => uen_c1_o,
			uen_p0_i => uen_p0_i,
			vsync_c1_o => vsync_c1_o,
			vsync_p0_i => vsync_p0_i
		);

		-- End of Generated Instance Port Map for ctrl

		-- Generated Instance Port Map for tnrc
		tnrc: di_tnrc
		port map (

			af_c0_i => af_c0,
			al_c0_i => al_c0,
			al_c1_i => al_c2,
			ap_c0_i => ap_c0,
			ap_p0_i => ap_p0_i,
			asresi_n => asresi_n,
			c_p0_i => c0_p0_i,
			c_p0_o => c0_p0_o,
			c_p1_i => c1_p1_i,
			c_p1_o => c1_p1_o,
			cblack_p_i => cblack_p_i,
			clkin => clkin,
			hsync_c_i => hsync_c,
			nr_dis_c_i => nr_dis_c_i,
			nron_iic_i => nron_iic_i,
			tnrabs_iic_i => tnrabs_iic_i,
			tnrclc_iic_i => tnrclc_iic_i,
			tnrkvaly_p_i => tnrkvaly,
			tnrs0c_iic_i => tnrs0c_iic_i,
			tnrs1c_iic_i => tnrs1c_iic_i,
			tnrs2c_iic_i => tnrs2c_iic_i,
			tnrs3c_iic_i => tnrs3c_iic_i,
			tnrs4c_iic_i => tnrs4c_iic_i,
			tnrs5c_iic_i => tnrs5c_iic_i,
			tnrs6c_iic_i => tnrs6c_iic_i,
			tnrs7c_iic_i => tnrs7c_iic_i,
			tnrsel_iic_i => tnrsel_iic_i,
			tnrssc_iic_i => tnrssc_iic_i
		);

		-- End of Generated Instance Port Map for tnrc

		-- Generated Instance Port Map for tnry
		tnry: di_tnry
		port map (

			af_c0_i => af_c0,
			al_c0_i => al_c0,
			al_c1_i => al_c2,
			ap_c0_i => ap_c0,
			ap_p0_i => ap_p0_i,
			asresi_n => asresi_n,
			clkin => clkin,
			hsync_c_i => hsync_c,
			nr_dis_c_i => nr_dis_c_i,
			nron_iic_i => nron_iic_i,
			tnrabs_iic_i => tnrabs_iic_i,
			tnrcly_iic_i => tnrcly_iic_i,
			tnrkvaly_p_o => tnrkvaly,
			tnrmd4y_iic_i => tnrmd4y_iic_i,
			tnrnr4y_iic_i => tnrnr4y_iic_i,
			tnrs0y_iic_i => tnrs0y_iic_i,
			tnrs1y_iic_i => tnrs1y_iic_i,
			tnrs2y_iic_i => tnrs2y_iic_i,
			tnrs3y_iic_i => tnrs3y_iic_i,
			tnrs4y_iic_i => tnrs4y_iic_i,
			tnrs5y_iic_i => tnrs5y_iic_i,
			tnrs6y_iic_i => tnrs6y_iic_i,
			tnrs7y_iic_i => tnrs7y_iic_i,
			tnrssy_iic_i => tnrssy_iic_i,
			y0_p1_i => y2_p1_i,
			y0_p1_o => y2_p1_o,
			y1_p1_i => y1_p1_i,
			y1_p1_o => y1_p1_o,
			y_p0_i => y0_p0_i,
			y_p0_o => y0_p0_o,
			yblack_p_i => yblack_p_i
		);

		-- End of Generated Instance Port Map for tnry



end struct;


--
--!End of Architecture/s
-- --------------------------------------------------------------
