-- -------------------------------------------------------------
--
--  Entity Declaration for di_tnr_ctrl
--
-- Generated
--  by:  lutscher
--  on:  Tue Jun 23 14:19:39 2009
--  cmd: /home/lutscher/work/MIX/mix_1.pl di_tnr.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Entity Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
--
-- Generator: mix_1.pl Version: Revision: 1.3 , wilfried.gaensheimer@micronas.com
-- (C) 2003,2005 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/enty


--

--
-- Start of Generated Entity di_tnr_ctrl
--
entity di_tnr_ctrl is

	-- Generics:
		-- No Generated Generics for Entity di_tnr_ctrl

	-- Generated Port Declaration:
		port(
		-- Generated Port for Entity di_tnr_ctrl
			af_c0_o	: out	std_ulogic ;
			af_c1_o	: out	std_ulogic;
			af_p0_i	: in	std_ulogic;
			al_c0_o	: out	std_ulogic;
			al_c1_o	: out	std_ulogic;
			al_c2_o	: out	std_ulogic;
			al_p0_i	: in	std_ulogic;
			ap_c0_o	: out	std_ulogic;
			ap_c1_o	: out	std_ulogic;
			ap_p0_i	: in	std_ulogic;
			asresi_n	: in	std_ulogic;
			clkin	: in	std_ulogic;
			field_p0_i	: in	std_ulogic;
			fieldc_c1_o	: out	std_ulogic;
			fieldy0_c1_o	: out	std_ulogic;
			fieldy1_c1_o	: out	std_ulogic;
			frafiesel_iic_i	: in	std_ulogic;
			hsync_c1_o	: out	std_ulogic;
			hsync_p0_i	: in	std_ulogic;
			hsync_p0_o	: out	std_ulogic;
			req_p1_o	: out	std_ulogic;
			tnrmdnr4c_iic_i	: in	std_ulogic;
			tnrnr4y_iic_i	: in	std_ulogic;
			uen_c1_o	: out	std_ulogic;
			uen_p0_i	: in	std_ulogic;
			vsync_c1_o	: out	std_ulogic;
			vsync_p0_i	: in	std_ulogic
		-- End of Generated Port for Entity di_tnr_ctrl
		);
end di_tnr_ctrl;
--
-- End of Generated Entity di_tnr_ctrl
--


--
--!End of Entity/ies
-- --------------------------------------------------------------
