-- -------------------------------------------------------------
-- MIX Configuration Template
--
-- (C) 2002 Micronas GmbH

-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author: lutscher $
-- $Id: mix_template-conf-c.vhd,v 1.1 2009/12/15 12:02:53 lutscher Exp $
-- $Date: 2009/12/15 12:02:53 $
-- $Log: mix_template-conf-c.vhd,v $
-- Revision 1.1  2009/12/15 12:02:53  lutscher
-- initial release
--
-- Revision 1.1  2003/03/25 13:49:01  wig
-- VHDL Templates
--
--
-- Generator: %0%%VERSION%, wilfried.gaensheimer@micronas.com
--
-- --------------------------------------------------------------
--weg: Library IEEE;
--weg: Use IEEE.std_logic_1164.all;
--weg: Use IEEE.std_logic_arith.all;

CONFIGURATION %CONF% OF %ENTY% is
	FOR %ARCH%
		
		FOR %INST%: %ENTY% 
			use configuration %CONF%;
		END FOR;
		FOR %INST%: %ENTY%
			use configuration %CONF%;
		END FOR;

	END FOR;
END %CONF%;

--!End