// -------------------------------------------------------------
//
// Generated Architecture Declaration for rtl of blue
//
// Generated
//  by:  lutscher
//  on:  Fri Jun 26 13:24:43 2009
//  cmd: /tools/mix/1.9//mix_1.pl -vinc global_project.i -nodelta LP-blue-pin-list.xls LP-paris-pin-list.xls LP-reallity-pin-list.xls LP-HIER.xls
//
// !!! Do not edit this file! Autogenerated by MIX !!!
// $Author$
// $Id$
// $Date$
// $Log$
//
// Based on Mix Verilog Architecture Template built into RCSfile: MixWriter.pm,v 
// Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
//
// Generator: mix_1.pl Revision: 1.3 , wilfried.gaensheimer@micronas.com
// (C) 2003,2005 Micronas GmbH
//
// --------------------------------------------------------------


`timescale 1ns/10ps


`include "global_project.i"

//
//
// Start of Generated Module rtl of blue
//

// No user `defines in this module


module blue
//
// Generated Module blue_i1
//
	(
		test1_i,	// from paris
		bla_o,	// to paris
		in2_i,	// from reallity
		in2_test_i,	// from reallity
		sig3_i,	// from reallity
		sig_i,	// from reallity
		out2_o,	// to reallity
		in3_i,	// from paris
		in4_i,	// from paris
		extin1_i,	// from EXTERNAL
		extout1_o,	// to EXTERNAL, to reallity
		extout2_o,	// to EXTERNAL, to reallity
		bla10_i,	// from paris
		teste_o,	// to paris
		vec_in_i,	// testtesttesttesttesttesttesttest
		vec_out_o,	// testtesttesttest
		gh_o,	// to paris
		tes_o,	// to reallity
		test5_o,	// to reallity
		bla1_i,	// from paris
		test_i,	// from reallity
		gimick_i,	// from reallity
		blub_o	// to paris
	);

	// Generated Module Inputs:
		input	[12:0]	test1_i;
		input	[15:0]	in2_test_i;
		input	[2:0]	sig3_i;
		input	[31:0]	in2_i;
		input		sig_i;
		input		in3_i;
		input	[3:0]	in4_i;
		input		extin1_i;
		input		bla10_i;
		input	[7:0]	vec_in_i;
		input		bla1_i;
		input		test_i;
		input		gimick_i;
	// Generated Module Outputs:
		output		bla_o;
		output		out2_o;
		output		extout1_o;
		output		extout2_o;
		output		teste_o;
		output	[3:0]	vec_out_o;
		output		gh_o;
		output		tes_o;
		output		test5_o;
		output		blub_o;
	// Generated Wires:
		wire	[12:0]	test1_i;
		wire		bla_o;
		wire		sig_i;
		wire	[15:0]	in2_test_i;
		wire	[2:0]	sig3_i;
		wire	[31:0]	in2_i;
		wire		out2_o;
		wire		in3_i;
		wire	[3:0]	in4_i;
		wire		extin1_i;
		wire		extout1_o;
		wire		extout2_o;
		wire		bla10_i;
		wire		teste_o;
		wire	[7:0]	vec_in_i;
		wire	[3:0]	vec_out_o;
		wire		gh_o;
		wire		tes_o;
		wire		test5_o;
		wire		bla1_i;
		wire		test_i;
		wire		gimick_i;
		wire		blub_o;
// End of generated module header


	// Internal signals

	//
	// Generated Signal List
	//
	//
	// End of Generated Signal List
	//


	// %COMPILER_OPTS%

	//
	// Generated Signal Assignments
	//




	//
	// Generated Instances and Port Mappings
	//


endmodule
//
// End of Generated Module rtl of blue
//

//
//!End of Module/s
// --------------------------------------------------------------
