// -------------------------------------------------------------
//
// Generated Architecture Declaration for rtl of pad
//
// Generated
//  by:  lutscher
//  on:  Fri Jun 26 13:24:43 2009
//  cmd: /tools/mix/1.9//mix_1.pl -vinc global_project.i -nodelta LP-blue-pin-list.xls LP-paris-pin-list.xls LP-reallity-pin-list.xls LP-HIER.xls
//
// !!! Do not edit this file! Autogenerated by MIX !!!
// $Author$
// $Id$
// $Date$
// $Log$
//
// Based on Mix Verilog Architecture Template built into RCSfile: MixWriter.pm,v 
// Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
//
// Generator: mix_1.pl Revision: 1.3 , wilfried.gaensheimer@micronas.com
// (C) 2003,2005 Micronas GmbH
//
// --------------------------------------------------------------


`timescale 1ns/10ps



//
//
// Start of Generated Module rtl of pad
//

// No user `defines in this module


module pad
//
// Generated Module bidi_bpad
//
	(
		DI,	// PAD <-> Iocell connect (IO)
		PAD,	// PAD <-> Iocell connect (IO)
		DO,	// PAD <-> Iocell connect (IO)
		EN	// PAD <-> Iocell connect (IO)
	);

	// Generated Module Inputs:
		input		DO;
		input		EN;
	// Generated Module In/Outputs:
		inout		PAD;
	// Generated Module Outputs:
		output		DI;
	// Generated Wires:
		wire		DI;
		wire		PAD;
		wire		DO;
		wire		EN;
// End of generated module header


	// Internal signals

	//
	// Generated Signal List
	//
	//
	// End of Generated Signal List
	//


	// %COMPILER_OPTS%

	//
	// Generated Signal Assignments
	//




	//
	// Generated Instances and Port Mappings
	//


endmodule
//
// End of Generated Module rtl of pad
//

//
//!End of Module/s
// --------------------------------------------------------------
