// -------------------------------------------------------------
//
// Generated Architecture Declaration for rtl of reallity
//
// Generated
//  by:  lutscher
//  on:  Fri Jun 26 13:24:43 2009
//  cmd: /tools/mix/1.9//mix_1.pl -vinc global_project.i -nodelta LP-blue-pin-list.xls LP-paris-pin-list.xls LP-reallity-pin-list.xls LP-HIER.xls
//
// !!! Do not edit this file! Autogenerated by MIX !!!
// $Author$
// $Id$
// $Date$
// $Log$
//
// Based on Mix Verilog Architecture Template built into RCSfile: MixWriter.pm,v 
// Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
//
// Generator: mix_1.pl Revision: 1.3 , wilfried.gaensheimer@micronas.com
// (C) 2003,2005 Micronas GmbH
//
// --------------------------------------------------------------


`timescale 1ns/10ps


`include "global_project.i"

//
//
// Start of Generated Module rtl of reallity
//

// No user `defines in this module


module reallity
//
// Generated Module reallity_i1
//
	(
		in2_o,	// to blue
		out2_i,	// from blue
		tes_i,	// from blue
		test5_i,	// from blue
		test_o,	// to blue
		gimick_o,	// to blue
		sig_o,	// to blue
		extout1_i,	// from blue
		extout2_i	// from blue
	);

	// Generated Module Inputs:
		input		out2_i;
		input		tes_i;
		input		test5_i;
		input		extout1_i;
		input		extout2_i;
	// Generated Module Outputs:
		output	[31:0]	in2_o;
		output		test_o;
		output		gimick_o;
		output		sig_o;
	// Generated Wires:
		wire	[31:0]	in2_o;
		wire		out2_i;
		wire		tes_i;
		wire		test5_i;
		wire		test_o;
		wire		gimick_o;
		wire		sig_o;
		wire		extout1_i;
		wire		extout2_i;
// End of generated module header


	// Internal signals

	//
	// Generated Signal List
	//
	//
	// End of Generated Signal List
	//


	// %COMPILER_OPTS%

	//
	// Generated Signal Assignments
	//




	//
	// Generated Instances and Port Mappings
	//


endmodule
//
// End of Generated Module rtl of reallity
//

//
//!End of Module/s
// --------------------------------------------------------------
