/**
 * Copyright (C) 1991,92,95,96,97,98,99,2000,01 Free Software Foundation, Inc.
 *
 * File: perlxsi.c - Perl XS Interface 
 *
 * This code, which is needed for dynamic module loading, is autogenerated 
 * by Perl using the command: 
 *
 *    $ perl -MExtUtils::Embed -e xsinit -- -o perlxsi.h
 *
 */

#include <EXTERN.h>
#include <perl.h>

EXTERN_C void xs_init (pTHX);

EXTERN_C void boot_DynaLoader (pTHX_ CV* cv);

EXTERN_C void

xs_init(pTHX)
{
    char *file = __FILE__;
    dXSUB_SYS;

    /* DynaLoader is a special case */
    newXS("DynaLoader::boot_DynaLoader", boot_DynaLoader, file);
}
