// -------------------------------------------------------------
//
// Generated Architecture Declaration for rtl of lp_bs
//
// Generated
//  by:  lutscher
//  on:  Fri Jun 26 13:24:43 2009
//  cmd: /tools/mix/1.9//mix_1.pl -vinc global_project.i -nodelta LP-blue-pin-list.xls LP-paris-pin-list.xls LP-reallity-pin-list.xls LP-HIER.xls
//
// !!! Do not edit this file! Autogenerated by MIX !!!
// $Author$
// $Id$
// $Date$
// $Log$
//
// Based on Mix Verilog Architecture Template built into RCSfile: MixWriter.pm,v 
// Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
//
// Generator: mix_1.pl Revision: 1.3 , wilfried.gaensheimer@micronas.com
// (C) 2003,2005 Micronas GmbH
//
// --------------------------------------------------------------


`timescale 1ns/10ps



//
//
// Start of Generated Module rtl of lp_bs
//

// No user `defines in this module


module lp_bs
//
// Generated Module lp_bs_i1
//
	(
		ext0_pad_di,
		vec_in_0_pad_di,
		vec_in_1_pad_di,
		vec_in_2_pad_di,
		vec_in_3_pad_di,
		vec_in_4_pad_di,
		vec_in_5_pad_di,
		vec_in_6_pad_di,
		vec_in_7_pad_di,
		vec_out_0_pad_do,
		vec_out_1_pad_do,
		vec_out_2_pad_do,
		vec_out_3_pad_do,
		bidi_pad_di,
		bidi_pad_do,
		bidi_pad_en,
		ext1_pad_do,
		ext2_pad_do
	);

	// Generated Module Inputs:
		input		ext0_pad_di;
		input		vec_in_0_pad_di;
		input		vec_in_1_pad_di;
		input		vec_in_2_pad_di;
		input		vec_in_3_pad_di;
		input		vec_in_4_pad_di;
		input		vec_in_5_pad_di;
		input		vec_in_6_pad_di;
		input		vec_in_7_pad_di;
		input		bidi_pad_di;
		input		ext1_pad_do;
		input		ext2_pad_do;
	// Generated Module Outputs:
		output		vec_out_0_pad_do;
		output		vec_out_1_pad_do;
		output		vec_out_2_pad_do;
		output		vec_out_3_pad_do;
		output		bidi_pad_do;
		output		bidi_pad_en;
	// Generated Wires:
		wire		ext0_pad_di;
		wire		vec_in_0_pad_di;
		wire		vec_in_1_pad_di;
		wire		vec_in_2_pad_di;
		wire		vec_in_3_pad_di;
		wire		vec_in_4_pad_di;
		wire		vec_in_5_pad_di;
		wire		vec_in_6_pad_di;
		wire		vec_in_7_pad_di;
		wire		vec_out_0_pad_do;
		wire		vec_out_1_pad_do;
		wire		vec_out_2_pad_do;
		wire		vec_out_3_pad_do;
		wire		bidi_pad_di;
		wire		bidi_pad_do;
		wire		bidi_pad_en;
		wire		ext1_pad_do;
		wire		ext2_pad_do;
// End of generated module header


	// Internal signals

	//
	// Generated Signal List
	//
		wire		blue_out2_s; 
		wire		reallity_gimick_s; 
		wire	[31:0]	reallity_in2_s; 
		wire		reallity_test_s; 
		wire		tes_s; 
		wire		test5_s; 
	//
	// End of Generated Signal List
	//


	// %COMPILER_OPTS%

	//
	// Generated Signal Assignments
	//




	//
	// Generated Instances and Port Mappings
	//
		// Generated Instance Port Map for lp_core_i1
		lp_core lp_core_i1 (	// LP core

			.bidi_pad_di(bidi_pad_di),	// from EXTERNALPAD <-> Iocell connect (IO)
			.bidi_pad_do(bidi_pad_do),	// to EXTERNALPAD <-> Iocell connect (IO)
			.bidi_pad_en(bidi_pad_en),	// to EXTERNALPAD <-> Iocell connect (IO)
			.blue_out2_s(blue_out2_s),	// to reallityfrom blue
			.ext0_pad_di(ext0_pad_di),	// from EXTERNALPAD <-> Iocell connect (IO)
			.reallity_gimick_s(reallity_gimick_s),	// from reallityto blue
			.reallity_in2_s(reallity_in2_s),	// from reallity (X4)to blue
			.reallity_test_s(reallity_test_s),	// from reallityto blue
			.tes_s(tes_s),	// to reallityfrom blue
			.test5_s(test5_s),	// to reallityfrom blue
			.vec_in_0_pad_di(vec_in_0_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_1_pad_di(vec_in_1_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_2_pad_di(vec_in_2_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_3_pad_di(vec_in_3_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_4_pad_di(vec_in_4_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_5_pad_di(vec_in_5_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_6_pad_di(vec_in_6_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_in_7_pad_di(vec_in_7_pad_di),	// testPAD <-> Iocell connect (IO)
			.vec_out_0_pad_do(vec_out_0_pad_do),	// testPAD <-> Iocell connect (IO)
			.vec_out_1_pad_do(vec_out_1_pad_do),	// testPAD <-> Iocell connect (IO)
			.vec_out_2_pad_do(vec_out_2_pad_do),	// testPAD <-> Iocell connect (IO)
			.vec_out_3_pad_do(vec_out_3_pad_do)	// testPAD <-> Iocell connect (IO)
		);
		// End of Generated Instance Port Map for lp_core_i1

		// Generated Instance Port Map for lp_stdby_i1
		lp_stdby lp_stdby_i1 (	// LP stdby

			.blue_out2_s(blue_out2_s),	// to reallityfrom blue
			.ext1_pad_do(ext1_pad_do),	// from bluePAD <-> Iocell connect (IO)
			.ext2_pad_do(ext2_pad_do),	// from bluePAD <-> Iocell connect (IO)
			.reallity_gimick_s(reallity_gimick_s),	// from reallityto blue
			.reallity_in2_s(reallity_in2_s),	// from reallity (X4)to blue
			.reallity_test_s(reallity_test_s),	// from reallityto blue
			.tes_s(tes_s),	// to reallityfrom blue
			.test5_s(test5_s)	// to reallityfrom blue
		);
		// End of Generated Instance Port Map for lp_stdby_i1



endmodule
//
// End of Generated Module rtl of lp_bs
//

//
//!End of Module/s
// --------------------------------------------------------------
