-- -------------------------------------------------------------
--
--  Entity Declaration for __COMMON__
--
-- Generated
--  by:  lutscher
--  on:  Tue Jun 23 10:43:20 2009
--  cmd: /home/lutscher/work/MIX/mix_1.pl a_clk.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Entity Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
--
-- Generator: mix_1.pl Version: Revision: 1.3 , wilfried.gaensheimer@micronas.com
-- (C) 2003,2005 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/enty


--

--
-- Start of Generated Entity A_CLK
--
entity A_CLK is

	-- Generics:
		-- No Generated Generics for Entity A_CLK

	-- Generated Port Declaration:
		port(
		-- Generated Port for Entity A_CLK
			alarm_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			clk	: in	std_ulogic;
			current_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			display_ls_hr	: out	std_ulogic_vector(6 downto 0);
			display_ls_min	: out	std_ulogic_vector(6 downto 0);
			display_ms_hr	: out	std_ulogic_vector(6 downto 0);
			display_ms_min	: out	std_ulogic_vector(6 downto 0);
			key_buffer_0	: in	std_ulogic_vector(3 downto 0);
			key_buffer_1	: in	std_ulogic_vector(3 downto 0);
			key_buffer_2	: in	std_ulogic_vector(3 downto 0);
			key_buffer_3	: in	std_ulogic_vector(3 downto 0);
			pad_conn_1_2	: in	std_ulogic;
			pad_conn_2_3	: in	std_ulogic;
			pad_conn_3_4	: in	std_ulogic;
			pad_conn_4_5	: in	std_ulogic;
			pad_conn_5_6	: in	std_ulogic;
			pad_conn_6_7	: in	std_ulogic;
			pad_conn_7_8	: in	std_ulogic;
			pad_conn_8_9	: in	std_ulogic;
			pad_conn_9_10	: in	std_ulogic;
			reset	: in	std_ulogic;
			show_a	: in	std_ulogic;
			show_new_time	: in	std_ulogic;
			sound_alarm	: out	std_ulogic;
			stopwatch	: in	std_ulogic
		-- End of Generated Port for Entity A_CLK
		);
end A_CLK;
--
-- End of Generated Entity A_CLK
--

--
-- Start of Generated Entity PADS
--
entity PADS is

	-- Generics:
		-- No Generated Generics for Entity PADS

	-- Generated Port Declaration:
		port(
		-- Generated Port for Entity PADS
			p_mix_pad_conn_1_2_go	: out	std_ulogic;
			p_mix_pad_conn_2_3_go	: out	std_ulogic;
			p_mix_pad_conn_3_4_go	: out	std_ulogic;
			p_mix_pad_conn_4_5_go	: out	std_ulogic;
			p_mix_pad_conn_5_6_go	: out	std_ulogic;
			p_mix_pad_conn_6_7_go	: out	std_ulogic;
			p_mix_pad_conn_7_8_go	: out	std_ulogic;
			p_mix_pad_conn_8_9_go	: out	std_ulogic;
			p_mix_pad_conn_9_10_go	: out	std_ulogic
		-- End of Generated Port for Entity PADS
		);
end PADS;
--
-- End of Generated Entity PADS
--

--
-- Start of Generated Entity ddrv4
--
entity ddrv4 is

	-- Generics:
		-- No Generated Generics for Entity ddrv4

	-- Generated Port Declaration:
		port(
		-- Generated Port for Entity ddrv4
			alarm_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			clk	: in	std_ulogic;
			current_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			display_ls_hr	: out	std_ulogic_vector(6 downto 0);
			display_ls_min	: out	std_ulogic_vector(6 downto 0);
			display_ms_hr	: out	std_ulogic_vector(6 downto 0);
			display_ms_min	: out	std_ulogic_vector(6 downto 0);
			key_buffer_0	: in	std_ulogic_vector(3 downto 0);
			key_buffer_1	: in	std_ulogic_vector(3 downto 0);
			key_buffer_2	: in	std_ulogic_vector(3 downto 0);
			key_buffer_3	: in	std_ulogic_vector(3 downto 0);
			p_mix_sound_alarm_test1_go	: out	std_ulogic;
			reset	: in	std_ulogic;	-- The Reset
			show_a	: in	std_ulogic;
			show_new_time	: in	std_ulogic;
			sound_alarm	: out	std_ulogic
		-- End of Generated Port for Entity ddrv4
		);
end ddrv4;
--
-- End of Generated Entity ddrv4
--


--
--!End of Entity/ies
-- --------------------------------------------------------------
