-- -------------------------------------------------------------
--
-- Generated Architecture Declaration for A_CLK_struct
--
-- Generated by wig
--           on Wed Jan 29 16:39:40 2003
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Architecture Template
--
-- Generator: mix_0.pl /mix/0.1, wilfried.gaensheimer@micronas.com
-- (C) 2003 Micronas GmbH
--
-- --------------------------------------------------------------
Library IEEE;
Use IEEE.std_logic_1164.all;
Use IEEE.std_logic_arith.all;

--
--
-- Start of Generated Architecture A_CLK_struct
--
architecture A_CLK_struct of A_CLK is 

	--
	-- Components
	--

	-- Generated Components
			component PADS
			
			port (
			-- generated
			-- NO IN PORTs	: 	;
			-- NO OUT PORTs	: 	
			-- end of generated port

			);
			end component;
		-- ---------

			component a_fsm
			
			port (
			-- generated
			alarm_button	: in	std_ulogic;
			alarm_in_u	: in	std_ulogic;
			clk	: in	std_ulogic;
			key	: in	std_ulogic_vector(3 downto 0);
			load_new_a	: out	std_ulogic;
			load_new_c	: out	std_ulogic;
			one_second	: in	std_ulogic;
			reset	: in	std_ulogic;
			shift	: out	std_ulogic;
			show_a	: out	std_ulogic;
			show_new_time	: out	std_ulogic;
			time_button	: in	std_ulogic;
			wire_high_bit	: in	__E_TYPE_MISMATCH(3 downto 0);
			wire_high_bus	: in	__E_TYPE_MISMATCH(3 downto 0);
			wire_low_bus	: in	__E_TYPE_MISMATCH(3 downto 0)
			-- end of generated port

			);
			end component;
		-- ---------

			component alreg
			
			port (
			-- generated
			alarm_time	: out	std_ulogic_vector(3 downto 0);
			load_new_a	: in	std_ulogic;
			new_alarm_time	: in	std_ulogic_vector(3 downto 0);
			reset	: in	std_ulogic
			-- end of generated port

			);
			end component;
		-- ---------

			component count4
			
			port (
			-- generated
			clk	: in	std_ulogic;
			current_time_ls_hr	: out	std_ulogic_vector(3 downto 0);
			current_time_ls_min	: out	std_ulogic_vector(3 downto 0);
			current_time_ms_hr	: out	std_ulogic_vector(3 downto 0);
			current_time_ms_min	: out	std_ulogic_vector(3 downto 0);
			load_new_c	: in	std_ulogic;
			new_current_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			new_current_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			new_current_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			new_current_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			one_minute	: in	std_ulogic;
			reset	: in	std_ulogic
			-- end of generated port

			);
			end component;
		-- ---------

			component ddrv4
			
			port (
			-- generated
			P_MIX_sound_alarm_test1_GI	: in	std_ulogic;
			P_MIX_sound_alarm_test1_GO	: out	std_ulogic;
			alarm_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			clk	: in	std_ulogic;
			current_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			display_ls_hr	: out	std_ulogic_vector(6 downto 0);
			display_ls_min	: out	std_ulogic_vector(6 downto 0);
			display_ms_hr	: out	std_ulogic_vector(6 downto 0);
			display_ms_min	: out	std_ulogic_vector(6 downto 0);
			key_buffer_0	: in	std_ulogic_vector(3 downto 0);
			key_buffer_1	: in	std_ulogic_vector(3 downto 0);
			key_buffer_2	: in	std_ulogic_vector(3 downto 0);
			key_buffer_3	: in	std_ulogic_vector(3 downto 0);
			reset	: in	std_ulogic;
			show_a	: in	std_ulogic;
			show_new_time	: in	std_ulogic;
			sound_alarm	: out	std_ulogic
			-- end of generated port

			);
			end component;
		-- ---------

			component keypad
			
			port (
			-- generated
			clk	: in	std_ulogic;
			columns	: in	std_ulogic_vector(2 downto 0);
			reset	: in	std_ulogic;
			rows	: out	std_ulogic_vector(3 downto 0)
			-- end of generated port

			);
			end component;
		-- ---------

			component keyscan
			
			port (
			-- generated
			alarm_button	: out	std_ulogic;
			clk	: in	std_ulogic;
			columns	: out	std_ulogic_vector(2 downto 0);
			key	: out	std_ulogic_vector(3 downto 0);
			key_buffer_0	: out	std_ulogic_vector(3 downto 0);
			key_buffer_1	: out	std_ulogic_vector(3 downto 0);
			key_buffer_2	: out	std_ulogic_vector(3 downto 0);
			key_buffer_3	: out	std_ulogic_vector(3 downto 0);
			reset	: in	std_ulogic;
			rows	: in	std_ulogic_vector(3 downto 0);
			shift	: in	std_ulogic;
			time_button	: out	std_ulogic
			-- end of generated port

			);
			end component;
		-- ---------

			component timegen
			
			port (
			-- generated
			clk	: in	std_ulogic;
			one_minute	: out	std_ulogic;
			one_second	: out	std_ulogic;
			reset	: in	std_ulogic;
			stopwatch	: in	std_ulogic
			-- end of generated port

			);
			end component;
		-- ---------



	--
	-- Nets
	--

			--
			-- Generated Signals
			--
			signal	__LOGIC1__	: __E_TYPE_MISMATCH(3 downto 0);
			signal	__LOGIC0__	: __E_TYPE_MISMATCH(3 downto 0);
			signal	alarm_button	: std_ulogic;
			signal	alarm_time_ls_hr	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ls_min	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ms_hr	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ms_min	: std_ulogic_vector(3 downto 0);
			signal	clk	: std_ulogic;
			signal	columns	: std_ulogic_vector(2 downto 0);
			signal	current_time_ls_hr	: std_ulogic_vector(3 downto 0);
			signal	current_time_ls_min	: std_ulogic_vector(3 downto 0);
			signal	current_time_ms_hr	: std_ulogic_vector(3 downto 0);
			signal	current_time_ms_min	: std_ulogic_vector(3 downto 0);
			signal	display_ls_hr	: std_ulogic_vector(6 downto 0);
			signal	display_ls_min	: std_ulogic_vector(6 downto 0);
			signal	display_ms_hr	: std_ulogic_vector(6 downto 0);
			signal	display_ms_min	: std_ulogic_vector(6 downto 0);
			signal	key	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_0	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_1	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_2	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_3	: std_ulogic_vector(3 downto 0);
			signal	load_new_a	: std_ulogic;
			signal	load_new_c	: std_ulogic;
			signal	one_minute	: std_ulogic;
			signal	one_sec_pulse	: std_ulogic;
			signal	reset	: std_ulogic;
			signal	rows	: std_ulogic_vector(3 downto 0);
			signal	shift	: std_ulogic;
			signal	show_a	: std_ulogic;
			signal	show_new_time	: std_ulogic;
			signal	sound_alarm	: std_ulogic;
			signal	sound_alarm_test1	: std_ulogic;
			signal	stopwatch	: std_ulogic;
			signal	time_button	: std_ulogic;
			--
			-- End of Generated Signals
			--


	-- %CONSTANTS%

begin

	--
	-- Generated Concurrent Statements
	--

	-- Generated Signal Assignments
			__LOGIC1__ <= '0';
			__LOGIC0__ <= '0';


	--
	-- Generated Instances
	--

	-- Generated Instances and Port Mappings
			-- Generated Instance Port Map for PADS
			PADS: PADS PORT MAP(
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for control
			control: a_fsm PORT MAP(
				wire_high_bit => __LOGIC1__,
				wire_high_bus => __LOGIC1__,
				wire_low_bus => __LOGIC0__,
				alarm_button => alarm_button,
				clk => clk,
				key => key,
				one_second => one_sec_pulse,
				reset => reset,
				alarm_in_u => sound_alarm_test1,
				time_button => time_button,
				load_new_a => load_new_a,
				load_new_c => load_new_c,
				shift => shift,
				show_a => show_a,
				show_new_time => show_new_time
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u0_alreg
			u0_alreg: alreg PORT MAP(
				new_alarm_time => key_buffer_0,
				load_new_a => load_new_a,
				reset => reset,
				alarm_time => alarm_time_ls_min
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u1_alreg
			u1_alreg: alreg PORT MAP(
				new_alarm_time => key_buffer_1,
				load_new_a => load_new_a,
				reset => reset,
				alarm_time => alarm_time_ms_min
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u2_alreg
			u2_alreg: alreg PORT MAP(
				new_alarm_time => key_buffer_2,
				load_new_a => load_new_a,
				reset => reset,
				alarm_time => alarm_time_ls_hr
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u3_alreg
			u3_alreg: alreg PORT MAP(
				new_alarm_time => key_buffer_3,
				load_new_a => load_new_a,
				reset => reset,
				alarm_time => alarm_time_ms_hr
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u_counter
			u_counter: count4 PORT MAP(
				clk => clk,
				new_current_time_ls_min => key_buffer_0,
				new_current_time_ms_min => key_buffer_1,
				new_current_time_ls_hr => key_buffer_2,
				new_current_time_ms_hr => key_buffer_3,
				load_new_c => load_new_c,
				one_minute => one_minute,
				reset => reset,
				current_time_ls_hr => current_time_ls_hr,
				current_time_ls_min => current_time_ls_min,
				current_time_ms_hr => current_time_ms_hr,
				current_time_ms_min => current_time_ms_min
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u_ddrv4
			u_ddrv4: ddrv4 PORT MAP(
				alarm_time_ls_hr => alarm_time_ls_hr,
				alarm_time_ls_min => alarm_time_ls_min,
				alarm_time_ms_hr => alarm_time_ms_hr,
				alarm_time_ms_min => alarm_time_ms_min,
				clk => clk,
				current_time_ls_hr => current_time_ls_hr,
				current_time_ls_min => current_time_ls_min,
				current_time_ms_hr => current_time_ms_hr,
				current_time_ms_min => current_time_ms_min,
				key_buffer_0 => key_buffer_0,
				key_buffer_1 => key_buffer_1,
				key_buffer_2 => key_buffer_2,
				key_buffer_3 => key_buffer_3,
				reset => reset,
				show_a => show_a,
				show_new_time => show_new_time,
				P_MIX_sound_alarm_test1_GI => sound_alarm_test1,
				display_ls_hr => display_ls_hr,
				display_ls_min => display_ls_min,
				display_ms_hr => display_ms_hr,
				display_ms_min => display_ms_min,
				sound_alarm => sound_alarm,
				P_MIX_sound_alarm_test1_GO => sound_alarm_test1
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u_keypad
			u_keypad: keypad PORT MAP(
				clk => clk,
				columns => columns,
				reset => reset,
				rows => rows
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u_keyscan
			u_keyscan: keyscan PORT MAP(
				clk => clk,
				reset => reset,
				rows => rows,
				shift => shift,
				alarm_button => alarm_button,
				columns => columns,
				key => key,
				key_buffer_0 => key_buffer_0,
				key_buffer_1 => key_buffer_1,
				key_buffer_2 => key_buffer_2,
				key_buffer_3 => key_buffer_3,
				time_button => time_button
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u_timegen
			u_timegen: timegen PORT MAP(
				clk => clk,
				reset => reset,
				stopwatch => stopwatch,
				one_minute => one_minute,
				one_second => one_sec_pulse
			);
			-- End of Generated Instance Port Map


end A_CLK_struct;

--
--!End of Entity/ies
-- --------------------------------------------------------------
