-- -------------------------------------------------------------
--
-- Generated Architecture Declaration for __COMMON__ of __COMMON__
--
-- Generated
--  by:  lutscher
--  on:  Tue Jun 23 10:43:20 2009
--  cmd: /home/lutscher/work/MIX/mix_1.pl a_clk.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Architecture Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.109 2008/04/01 12:48:34 wig Exp 
--
-- Generator: mix_1.pl Revision: 1.3 , wilfried.gaensheimer@micronas.com
-- (C) 2003,2005 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/arch


--
--
-- Start of Generated Architecture rtl of A_CLK
--
architecture rtl of A_CLK is 

	--
	-- Generated Constant Declarations
	--


	--
	-- Generated Components
	--
	component PADS
		-- No Generated Generics
		port (
		-- Generated Port for Entity PADS
			p_mix_pad_conn_1_2_go	: out	std_ulogic;
			p_mix_pad_conn_2_3_go	: out	std_ulogic;
			p_mix_pad_conn_3_4_go	: out	std_ulogic;
			p_mix_pad_conn_4_5_go	: out	std_ulogic;
			p_mix_pad_conn_5_6_go	: out	std_ulogic;
			p_mix_pad_conn_6_7_go	: out	std_ulogic;
			p_mix_pad_conn_7_8_go	: out	std_ulogic;
			p_mix_pad_conn_8_9_go	: out	std_ulogic;
			p_mix_pad_conn_9_10_go	: out	std_ulogic
		-- End of Generated Port for Entity PADS
		);
	end component;
	-- ---------

	component a_fsm
		-- No Generated Generics
		port (
		-- Generated Port for Entity a_fsm
			alarm_button	: in	std_ulogic;
			alarm_in_u	: in	std_ulogic;
			clk	: in	std_ulogic;
			key	: in	std_ulogic_vector(3 downto 0);
			load_new_a	: out	std_ulogic;
			load_new_c	: out	std_ulogic;
			one_second	: in	std_ulogic;
			reset	: in	std_ulogic;
			shift	: out	std_ulogic;
			show_a	: out	std_ulogic;
			show_new_time	: out	std_ulogic;
			time_button	: in	std_ulogic;
			wire_high_bit	: in	std_ulogic;	--  Wire bit to high
			wire_high_bus	: in	std_ulogic_vector(3 downto 0);	-- Ground wire_low port
			wire_low_bus	: in	std_ulogic_vector(3 downto 0)	-- Ground wire_low port
		-- End of Generated Port for Entity a_fsm
		);
	end component;
	-- ---------

	component alreg
		-- No Generated Generics
		port (
		-- Generated Port for Entity alreg
			alarm_time	: out	std_ulogic_vector(3 downto 0);
			load_new_a	: in	std_ulogic;
			new_alarm_time	: in	std_ulogic_vector(3 downto 0);
			reset	: in	std_ulogic	-- The Reset
		-- End of Generated Port for Entity alreg
		);
	end component;
	-- ---------

	component count4
		-- No Generated Generics
		port (
		-- Generated Port for Entity count4
			clk	: in	std_ulogic;
			current_time_ls_hr	: out	std_ulogic_vector(3 downto 0);
			current_time_ls_min	: out	std_ulogic_vector(3 downto 0);
			current_time_ms_hr	: out	std_ulogic_vector(3 downto 0);
			current_time_ms_min	: out	std_ulogic_vector(3 downto 0);
			load_new_c	: in	std_ulogic;
			new_current_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			new_current_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			new_current_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			new_current_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			one_minute	: in	std_ulogic;
			reset	: in	std_ulogic	-- The Reset
		-- End of Generated Port for Entity count4
		);
	end component;
	-- ---------

	component ddrv4
		-- No Generated Generics
		port (
		-- Generated Port for Entity ddrv4
			alarm_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			alarm_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			clk	: in	std_ulogic;
			current_time_ls_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ls_min	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_hr	: in	std_ulogic_vector(3 downto 0);
			current_time_ms_min	: in	std_ulogic_vector(3 downto 0);
			display_ls_hr	: out	std_ulogic_vector(6 downto 0);
			display_ls_min	: out	std_ulogic_vector(6 downto 0);
			display_ms_hr	: out	std_ulogic_vector(6 downto 0);
			display_ms_min	: out	std_ulogic_vector(6 downto 0);
			key_buffer_0	: in	std_ulogic_vector(3 downto 0);
			key_buffer_1	: in	std_ulogic_vector(3 downto 0);
			key_buffer_2	: in	std_ulogic_vector(3 downto 0);
			key_buffer_3	: in	std_ulogic_vector(3 downto 0);
			p_mix_sound_alarm_test1_go	: out	std_ulogic;
			reset	: in	std_ulogic;	-- The Reset
			show_a	: in	std_ulogic;
			show_new_time	: in	std_ulogic;
			sound_alarm	: out	std_ulogic
		-- End of Generated Port for Entity ddrv4
		);
	end component;
	-- ---------

	component keypad
		-- No Generated Generics
		port (
		-- Generated Port for Entity keypad
			clk	: in	std_ulogic;
			columns	: in	std_ulogic_vector(2 downto 0);
			reset	: in	std_ulogic;	-- The Reset
			rows	: out	std_ulogic_vector(3 downto 0)	-- Keypad Output
		-- End of Generated Port for Entity keypad
		);
	end component;
	-- ---------

	component keyscan
		-- No Generated Generics
		port (
		-- Generated Port for Entity keyscan
			alarm_button	: out	std_ulogic;
			clk	: in	std_ulogic;
			columns	: out	std_ulogic_vector(2 downto 0);
			key	: out	std_ulogic_vector(3 downto 0);
			key_buffer_0	: out	std_ulogic_vector(3 downto 0);
			key_buffer_1	: out	std_ulogic_vector(3 downto 0);
			key_buffer_2	: out	std_ulogic_vector(3 downto 0);
			key_buffer_3	: out	std_ulogic_vector(3 downto 0);
			reset	: in	std_ulogic;	-- The Reset
			rows	: in	std_ulogic_vector(3 downto 0);	-- Keypad Output
			shift	: in	std_ulogic;
			time_button	: out	std_ulogic
		-- End of Generated Port for Entity keyscan
		);
	end component;
	-- ---------

	component timegen
		-- No Generated Generics
		port (
		-- Generated Port for Entity timegen
			clk	: in	std_ulogic;
			one_minute	: out	std_ulogic;
			one_second	: out	std_ulogic;
			reset	: in	std_ulogic;	-- The Reset
			stopwatch	: in	std_ulogic	-- Driven by reset
		-- End of Generated Port for Entity timegen
		);
	end component;
	-- ---------



	--
	-- Generated Signal List
	--
		signal	mix_logic1_0	: std_ulogic; 
		signal	mix_logic1_bus_1	: std_ulogic_vector(3 downto 0); 
		signal	mix_logic0_bus_1	: std_ulogic_vector(3 downto 0); 
		signal	alarm_button	: std_ulogic; 
		signal	s_int_alarm_time_ls_hr	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_alarm_time_ls_min	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_alarm_time_ms_hr	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_alarm_time_ms_min	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	columns	: std_ulogic_vector(2 downto 0); 
		signal	s_int_current_time_ls_hr	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_current_time_ls_min	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_current_time_ms_hr	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_current_time_ms_min	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	key	: std_ulogic_vector(3 downto 0); 
		signal	s_int_key_buffer_0	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_key_buffer_1	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_key_buffer_2	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_key_buffer_3	: std_ulogic_vector(3 downto 0); -- __W_PORT_SIGNAL_MAP_REQ
		signal	load_new_a	: std_ulogic; 
		signal	load_new_c	: std_ulogic; 
		signal	one_minute	: std_ulogic; 
		signal	one_sec_pulse	: std_ulogic; 
		signal	rows	: std_ulogic_vector(3 downto 0); 
		signal	shift	: std_ulogic; 
		signal	s_int_show_a	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	s_int_show_new_time	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	sound_alarm_test1	: std_ulogic; 
		signal	time_button	: std_ulogic; 
	--
	-- End of Generated Signal List
	--




begin


	--
	-- Generated Concurrent Statements
	--

	--
	-- Generated Signal Assignments
	--
		mix_logic1_0	<=	'1';
		mix_logic1_bus_1	<=	( others => '1' );
		mix_logic0_bus_1	<=	( others => '0' );
		s_int_alarm_time_ls_hr	<=	alarm_time_ls_hr;  -- __I_I_BUS_PORT
		s_int_alarm_time_ls_min	<=	alarm_time_ls_min;  -- __I_I_BUS_PORT
		s_int_alarm_time_ms_hr	<=	alarm_time_ms_hr;  -- __I_I_BUS_PORT
		s_int_alarm_time_ms_min	<=	alarm_time_ms_min;  -- __I_I_BUS_PORT
		s_int_current_time_ls_hr	<=	current_time_ls_hr;  -- __I_I_BUS_PORT
		s_int_current_time_ls_min	<=	current_time_ls_min;  -- __I_I_BUS_PORT
		s_int_current_time_ms_hr	<=	current_time_ms_hr;  -- __I_I_BUS_PORT
		s_int_current_time_ms_min	<=	current_time_ms_min;  -- __I_I_BUS_PORT
		s_int_key_buffer_0	<=	key_buffer_0;  -- __I_I_BUS_PORT
		s_int_key_buffer_1	<=	key_buffer_1;  -- __I_I_BUS_PORT
		s_int_key_buffer_2	<=	key_buffer_2;  -- __I_I_BUS_PORT
		s_int_key_buffer_3	<=	key_buffer_3;  -- __I_I_BUS_PORT
		s_int_show_a	<=	show_a;  -- __I_I_BIT_PORT
		s_int_show_new_time	<=	show_new_time;  -- __I_I_BIT_PORT


	--
	-- Generated Instances and Port Mappings
	--
		-- Generated Instance Port Map for PADS
		PADS: PADS
		port map (
			p_mix_pad_conn_1_2_go => pad_conn_1_2,
			p_mix_pad_conn_2_3_go => pad_conn_2_3,
			p_mix_pad_conn_3_4_go => pad_conn_3_4,
			p_mix_pad_conn_4_5_go => pad_conn_4_5,
			p_mix_pad_conn_5_6_go => pad_conn_5_6,
			p_mix_pad_conn_6_7_go => pad_conn_6_7,
			p_mix_pad_conn_7_8_go => pad_conn_7_8,
			p_mix_pad_conn_8_9_go => pad_conn_8_9,
			p_mix_pad_conn_9_10_go => pad_conn_9_10
		);

		-- End of Generated Instance Port Map for PADS

		-- Generated Instance Port Map for control
		control: a_fsm
		port map (

			alarm_button => alarm_button,
			alarm_in_u => sound_alarm_test1,	-- Use internally test1
			clk => clk,	-- The ClockThe d_Clk (X4)
			key => key,
			load_new_a => load_new_a,
			load_new_c => load_new_c,
			one_second => one_sec_pulse,
			reset => reset,	-- The Reset (X10)
			shift => shift,
			show_a => s_int_show_a,
			show_new_time => s_int_show_new_time,
			time_button => time_button,
			wire_high_bit => mix_logic1_0,	--  Wire bit to high
			wire_high_bus => mix_logic1_bus_1,	-- Ground wire_low port
			wire_low_bus => mix_logic0_bus_1	-- Ground wire_low port
		);

		-- End of Generated Instance Port Map for control

		-- Generated Instance Port Map for u0_alreg
		u0_alreg: alreg
		port map (

			alarm_time => s_int_alarm_time_ls_min,	-- Display storage buffer 0 ls_min
			load_new_a => load_new_a,
			new_alarm_time => s_int_key_buffer_0,	-- Display storage buffer 0 ls_min
			reset => reset	-- The Reset (X10)
		);

		-- End of Generated Instance Port Map for u0_alreg

		-- Generated Instance Port Map for u1_alreg
		u1_alreg: alreg
		port map (

			alarm_time => s_int_alarm_time_ms_min,	-- Display storage buffer 1 ms_min
			load_new_a => load_new_a,
			new_alarm_time => s_int_key_buffer_1,	-- Display storage buffer 1 ms_min
			reset => reset	-- The Reset (X10)
		);

		-- End of Generated Instance Port Map for u1_alreg

		-- Generated Instance Port Map for u2_alreg
		u2_alreg: alreg
		port map (

			alarm_time => s_int_alarm_time_ls_hr,	-- Display storage buffer 2 ls_hr
			load_new_a => load_new_a,
			new_alarm_time => s_int_key_buffer_2,	-- Display storage buffer 2 ls_hr
			reset => reset	-- The Reset (X10)
		);

		-- End of Generated Instance Port Map for u2_alreg

		-- Generated Instance Port Map for u3_alreg
		u3_alreg: alreg
		port map (

			alarm_time => s_int_alarm_time_ms_hr,	-- Display storage buffer 3 ms_hr
			load_new_a => load_new_a,
			new_alarm_time => s_int_key_buffer_3,	-- Display storage buffer 3 ms_hr
			reset => reset	-- The Reset (X10)
		);

		-- End of Generated Instance Port Map for u3_alreg

		-- Generated Instance Port Map for u_counter
		u_counter: count4
		port map (

			clk => clk,	-- The ClockThe d_Clk (X4)
			current_time_ls_hr => s_int_current_time_ls_hr,	-- Display storage buffer 2 ls_hr
			current_time_ls_min => s_int_current_time_ls_min,	-- Display storage buffer 0 ls_min
			current_time_ms_hr => s_int_current_time_ms_hr,	-- Display storage buffer 3 ms_hr
			current_time_ms_min => s_int_current_time_ms_min,	-- Display storage buffer 1 ms_min
			load_new_c => load_new_c,
			new_current_time_ls_hr => s_int_key_buffer_2,	-- Display storage buffer 2 ls_hr
			new_current_time_ls_min => s_int_key_buffer_0,	-- Display storage buffer 0 ls_min
			new_current_time_ms_hr => s_int_key_buffer_3,	-- Display storage buffer 3 ms_hr
			new_current_time_ms_min => s_int_key_buffer_1,	-- Display storage buffer 1 ms_min
			one_minute => one_minute,
			reset => reset	-- The Reset (X10)
		);

		-- End of Generated Instance Port Map for u_counter

		-- Generated Instance Port Map for u_ddrv4
		u_ddrv4: ddrv4
		port map (

			alarm_time_ls_hr => s_int_alarm_time_ls_hr,	-- Display storage buffer 2 ls_hr
			alarm_time_ls_min => s_int_alarm_time_ls_min,	-- Display storage buffer 0 ls_min
			alarm_time_ms_hr => s_int_alarm_time_ms_hr,	-- Display storage buffer 3 ms_hr
			alarm_time_ms_min => s_int_alarm_time_ms_min,	-- Display storage buffer 1 ms_min
			clk => clk,	-- The ClockThe d_Clk (X4)
			current_time_ls_hr => s_int_current_time_ls_hr,	-- Display storage buffer 2 ls_hr
			current_time_ls_min => s_int_current_time_ls_min,	-- Display storage buffer 0 ls_min
			current_time_ms_hr => s_int_current_time_ms_hr,	-- Display storage buffer 3 ms_hr
			current_time_ms_min => s_int_current_time_ms_min,	-- Display storage buffer 1 ms_min
			display_ls_hr => display_ls_hr,	-- Display storage buffer 2 ls_hr
			display_ls_min => display_ls_min,	-- Display storage buffer 0 ls_min
			display_ms_hr => display_ms_hr,	-- Display storage buffer 3 ms_hr
			display_ms_min => display_ms_min,	-- Display storage buffer 1 ms_min
			key_buffer_0 => s_int_key_buffer_0,	-- Display storage buffer 0 ls_min
			key_buffer_1 => s_int_key_buffer_1,	-- Display storage buffer 1 ms_min
			key_buffer_2 => s_int_key_buffer_2,	-- Display storage buffer 2 ls_hr
			key_buffer_3 => s_int_key_buffer_3,	-- Display storage buffer 3 ms_hr
			p_mix_sound_alarm_test1_go => sound_alarm_test1,	-- Use internally test1
			reset => reset,	-- The Reset (X10)
			show_a => s_int_show_a,
			show_new_time => s_int_show_new_time,
			sound_alarm => sound_alarm
		);

		-- End of Generated Instance Port Map for u_ddrv4

		-- Generated Instance Port Map for u_keypad
		u_keypad: keypad
		port map (

			clk => clk,	-- The ClockThe d_Clk (X4)
			columns => columns,
			reset => reset,	-- The Reset (X10)
			rows => rows	-- Keypad Output
		);

		-- End of Generated Instance Port Map for u_keypad

		-- Generated Instance Port Map for u_keyscan
		u_keyscan: keyscan
		port map (

			alarm_button => alarm_button,
			clk => clk,	-- The ClockThe d_Clk (X4)
			columns => columns,
			key => key,
			key_buffer_0 => s_int_key_buffer_0,	-- Display storage buffer 0 ls_min
			key_buffer_1 => s_int_key_buffer_1,	-- Display storage buffer 1 ms_min
			key_buffer_2 => s_int_key_buffer_2,	-- Display storage buffer 2 ls_hr
			key_buffer_3 => s_int_key_buffer_3,	-- Display storage buffer 3 ms_hr
			reset => reset,	-- The Reset (X10)
			rows => rows,	-- Keypad Output
			shift => shift,
			time_button => time_button
		);

		-- End of Generated Instance Port Map for u_keyscan

		-- Generated Instance Port Map for u_timegen
		u_timegen: timegen
		port map (

			clk => clk,	-- The ClockThe d_Clk (X4)
			one_minute => one_minute,
			one_second => one_sec_pulse,
			reset => reset,	-- The Reset (X10)
			stopwatch => stopwatch	-- Driven by reset
		);

		-- End of Generated Instance Port Map for u_timegen



end rtl;

--
-- Start of Generated Architecture rtl of PADS
--
architecture rtl of PADS is 

	--
	-- Generated Constant Declarations
	--


	--
	-- Generated Components
	--
	component padcell
		-- No Generated Generics
		port (
		-- Generated Port for Entity padcell
			EI	: in	std_ulogic;
			EO	: out	std_ulogic
		-- End of Generated Port for Entity padcell
		);
	end component;
	-- ---------



	--
	-- Generated Signal List
	--
		signal	mix_logic0_0	: std_ulogic; 
		signal	pad_conn_1_2	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_2_3	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_3_4	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_4_5	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_5_6	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_6_7	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_7_8	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_8_9	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
		signal	pad_conn_9_10	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
	--
	-- End of Generated Signal List
	--




begin


	--
	-- Generated Concurrent Statements
	--

	--
	-- Generated Signal Assignments
	--
		mix_logic0_0	<=	'0';
		p_mix_pad_conn_1_2_go	<=	pad_conn_1_2;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_2_3_go	<=	pad_conn_2_3;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_3_4_go	<=	pad_conn_3_4;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_4_5_go	<=	pad_conn_4_5;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_5_6_go	<=	pad_conn_5_6;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_6_7_go	<=	pad_conn_6_7;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_7_8_go	<=	pad_conn_7_8;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_8_9_go	<=	pad_conn_8_9;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)
		p_mix_pad_conn_9_10_go	<=	pad_conn_9_10;  -- __I_O_SLICE_PORT -- __I_SINGLE_BIT (0)


	--
	-- Generated Instances and Port Mappings
	--
		-- Generated Instance Port Map for Pad_1
		Pad_1: padcell
		port map (

			EI => mix_logic0_0,	-- Ground EI of Pad1
			EO => pad_conn_1_2
		);

		-- End of Generated Instance Port Map for Pad_1

		-- Generated Instance Port Map for Pad_10
		Pad_10: padcell
		port map (
			EI => pad_conn_9_10
		);

		-- End of Generated Instance Port Map for Pad_10

		-- Generated Instance Port Map for Pad_2
		Pad_2: padcell
		port map (

			EI => pad_conn_1_2,
			EO => pad_conn_2_3
		);

		-- End of Generated Instance Port Map for Pad_2

		-- Generated Instance Port Map for Pad_3
		Pad_3: padcell
		port map (

			EI => pad_conn_2_3,
			EO => pad_conn_3_4
		);

		-- End of Generated Instance Port Map for Pad_3

		-- Generated Instance Port Map for Pad_4
		Pad_4: padcell
		port map (

			EI => pad_conn_3_4,
			EO => pad_conn_4_5
		);

		-- End of Generated Instance Port Map for Pad_4

		-- Generated Instance Port Map for Pad_5
		Pad_5: padcell
		port map (

			EI => pad_conn_4_5,
			EO => pad_conn_5_6
		);

		-- End of Generated Instance Port Map for Pad_5

		-- Generated Instance Port Map for Pad_6
		Pad_6: padcell
		port map (

			EI => pad_conn_5_6,
			EO => pad_conn_6_7
		);

		-- End of Generated Instance Port Map for Pad_6

		-- Generated Instance Port Map for Pad_7
		Pad_7: padcell
		port map (

			EI => pad_conn_6_7,
			EO => pad_conn_7_8
		);

		-- End of Generated Instance Port Map for Pad_7

		-- Generated Instance Port Map for Pad_8
		Pad_8: padcell
		port map (

			EI => pad_conn_7_8,
			EO => pad_conn_8_9
		);

		-- End of Generated Instance Port Map for Pad_8

		-- Generated Instance Port Map for Pad_9
		Pad_9: padcell
		port map (

			EI => pad_conn_8_9,
			EO => pad_conn_9_10
		);

		-- End of Generated Instance Port Map for Pad_9



end rtl;

--
-- Start of Generated Architecture rtl of ddrv4
--
architecture rtl of ddrv4 is 

	--
	-- Generated Constant Declarations
	--


	--
	-- Generated Components
	--
	component ddrv
		-- No Generated Generics
		port (
		-- Generated Port for Entity ddrv
			alarm_in	: in	std_ulogic;	-- Use internally test1
			alarm_time	: in	std_ulogic_vector(3 downto 0);	-- Display storage buffer 1 ms_min
			clk	: in	std_ulogic;	-- The d_Clk
			current_time	: in	std_ulogic_vector(3 downto 0);	-- Display storage buffer 1 ms_min
			display	: out	std_ulogic_vector(6 downto 0);	-- Display storage buffer 1 ms_min
			key_buffer	: in	std_ulogic_vector(3 downto 0);	-- Display storage buffer 1 ms_min
			show_a	: in	std_ulogic;
			show_new_time	: in	std_ulogic;
			sound_alarm	: out	std_ulogic 	-- Display storage buffer 1 ms_min __I_AUTO_REDUCED_BUS2SIGNAL
		-- End of Generated Port for Entity ddrv
		);
	end component;
	-- ---------

	component and_f
		-- No Generated Generics
		port (
		-- Generated Port for Entity and_f
			clk	: in	std_ulogic;
			mix_key_out	: out	std_ulogic;
			out_2	: out	std_ulogic;	-- Use internally test1
			reset	: in	std_ulogic;	-- The Reset
			y	: in	std_ulogic_vector(3 downto 0)	-- Display storage buffer 3 ms_hr
		-- End of Generated Port for Entity and_f
		);
	end component;
	-- ---------



	--
	-- Generated Signal List
	--
		signal	alarm	: std_ulogic_vector(3 downto 0); 
		signal	sound_alarm_test1	: std_ulogic; -- __W_PORT_SIGNAL_MAP_REQ
	--
	-- End of Generated Signal List
	--




begin


	--
	-- Generated Concurrent Statements
	--

	--
	-- Generated Signal Assignments
	--
		p_mix_sound_alarm_test1_go	<=	sound_alarm_test1;  -- __I_O_BIT_PORT


	--
	-- Generated Instances and Port Mappings
	--
		-- Generated Instance Port Map for d_ls_hr
		d_ls_hr: ddrv
		port map (

			alarm_time => alarm_time_ls_hr,	-- Display storage buffer 2 ls_hr
			clk => clk,	-- The ClockThe d_Clk (X4)
			current_time => current_time_ls_hr,	-- Display storage buffer 2 ls_hr
			display => display_ls_hr,	-- Display storage buffer 2 ls_hr
			key_buffer => key_buffer_2,	-- Display storage buffer 2 ls_hr
			show_a => show_a,
			show_new_time => show_new_time,
			sound_alarm => alarm(2)	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
		);

		-- End of Generated Instance Port Map for d_ls_hr

		-- Generated Instance Port Map for d_ls_min
		d_ls_min: ddrv
		port map (

			alarm_time => alarm_time_ls_min,	-- Display storage buffer 0 ls_min
			clk => clk,	-- The ClockThe d_Clk (X4)
			current_time => current_time_ls_min,	-- Display storage buffer 0 ls_min
			display => display_ls_min,	-- Display storage buffer 0 ls_min
			key_buffer => key_buffer_0,	-- Display storage buffer 0 ls_min
			show_a => show_a,
			show_new_time => show_new_time,
			sound_alarm => alarm(0)	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
		);

		-- End of Generated Instance Port Map for d_ls_min

		-- Generated Instance Port Map for d_ms_hr
		d_ms_hr: ddrv
		port map (

			alarm_in => sound_alarm_test1,	-- Use internally test1
			alarm_time => alarm_time_ms_hr,	-- Display storage buffer 3 ms_hr
			clk => clk,	-- The ClockThe d_Clk (X4)
			current_time => current_time_ms_hr,	-- Display storage buffer 3 ms_hr
			display => display_ms_hr,	-- Display storage buffer 3 ms_hr
			key_buffer => key_buffer_3,	-- Display storage buffer 3 ms_hr
			show_a => show_a,
			show_new_time => show_new_time,
			sound_alarm => alarm(3)	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
		);

		-- End of Generated Instance Port Map for d_ms_hr

		-- Generated Instance Port Map for d_ms_min
		d_ms_min: ddrv
		port map (

			alarm_time => alarm_time_ms_min,	-- Display storage buffer 1 ms_min
			clk => clk,	-- The ClockThe d_Clk (X4)
			current_time => current_time_ms_min,	-- Display storage buffer 1 ms_min
			display => display_ms_min,	-- Display storage buffer 1 ms_min
			key_buffer => key_buffer_1,	-- Display storage buffer 1 ms_min
			show_a => show_a,
			show_new_time => show_new_time,
			sound_alarm => alarm(1)	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
		);

		-- End of Generated Instance Port Map for d_ms_min

		-- Generated Instance Port Map for u_and_f
		u_and_f: and_f
		port map (

			clk => clk,	-- The ClockThe d_Clk (X4)
			mix_key_out => sound_alarm,
			out_2 => sound_alarm_test1,	-- Use internally test1
			reset => reset,	-- The Reset (X10)
			y(0) => alarm(0),	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
			y(1) => alarm(0),	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
			y(2) => alarm(0),	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
			y(3) => alarm(0)	-- Display storage buffer 0 ls_minDisplay storage buffer 1 ms_minDisplay storage buffer 2 ls_hrDi...
		);

		-- End of Generated Instance Port Map for u_and_f



end rtl;


--
--!End of Architecture/s
-- --------------------------------------------------------------
