-- -------------------------------------------------------------
--
-- Generated Architecture Declaration for ddrv4_struct
--
-- Generated by wig
--           on Wed Jan 29 16:39:40 2003
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Architecture Template
--
-- Generator: mix_0.pl /mix/0.1, wilfried.gaensheimer@micronas.com
-- (C) 2003 Micronas GmbH
--
-- --------------------------------------------------------------
Library IEEE;
Use IEEE.std_logic_1164.all;
Use IEEE.std_logic_arith.all;

--
--
-- Start of Generated Architecture ddrv4_struct
--
architecture ddrv4_struct of ddrv4 is 

	--
	-- Components
	--

	-- Generated Components
			component ddrv
			
			port (
			-- generated
			alarm_in	: in	std_ulogic;
			alarm_time	: in	std_ulogic_vector(3 downto 0);
			clk	: in	std_ulogic;
			current_time	: in	std_ulogic_vector(3 downto 0);
			display	: out	std_ulogic_vector(6 downto 0);
			key_buffer	: in	std_ulogic_vector(3 downto 0);
			show_a	: in	std_ulogic;
			show_new_time	: in	std_ulogic;
			sound_alarm	: out	std_ulogic_vector(3 downto 0)
			-- end of generated port

			);
			end component;
		-- ---------

			component and_f
			
			port (
			-- generated
			clk	: in	std_ulogic;
			out	: out	std_ulogic;
			out_2	: out	std_ulogic;
			reset	: in	std_ulogic;
			y	: in	std_ulogic_vector(3 downto 0)
			-- end of generated port

			);
			end component;
		-- ---------



	--
	-- Nets
	--

			--
			-- Generated Signals
			--
			signal	alarm	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ls_hr	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ls_min	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ms_hr	: std_ulogic_vector(3 downto 0);
			signal	alarm_time_ms_min	: std_ulogic_vector(3 downto 0);
			signal	clk	: std_ulogic;
			signal	current_time_ls_hr	: std_ulogic_vector(3 downto 0);
			signal	current_time_ls_min	: std_ulogic_vector(3 downto 0);
			signal	current_time_ms_hr	: std_ulogic_vector(3 downto 0);
			signal	current_time_ms_min	: std_ulogic_vector(3 downto 0);
			signal	display_ls_hr	: std_ulogic_vector(6 downto 0);
			signal	display_ls_min	: std_ulogic_vector(6 downto 0);
			signal	display_ms_hr	: std_ulogic_vector(6 downto 0);
			signal	display_ms_min	: std_ulogic_vector(6 downto 0);
			signal	key_buffer_0	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_1	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_2	: std_ulogic_vector(3 downto 0);
			signal	key_buffer_3	: std_ulogic_vector(3 downto 0);
			signal	reset	: std_ulogic;
			signal	show_a	: std_ulogic;
			signal	show_new_time	: std_ulogic;
			signal	sound_alarm	: std_ulogic;
			signal	sound_alarm_test1	: std_ulogic;
			--
			-- End of Generated Signals
			--


	-- %CONSTANTS%

begin

	--
	-- Generated Concurrent Statements
	--

	-- Generated Signal Assignments


	--
	-- Generated Instances
	--

	-- Generated Instances and Port Mappings
			-- Generated Instance Port Map for d_ls_hr
			d_ls_hr: ddrv PORT MAP(
				alarm_time => alarm_time_ls_hr,
				clk => clk,
				current_time => current_time_ls_hr,
				key_buffer => key_buffer_2,
				show_a => show_a,
				show_new_time => show_new_time,
				sound_alarm => alarm,
				display => display_ls_hr
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for d_ls_min
			d_ls_min: ddrv PORT MAP(
				alarm_time => alarm_time_ls_min,
				clk => clk,
				current_time => current_time_ls_min,
				key_buffer => key_buffer_0,
				show_a => show_a,
				show_new_time => show_new_time,
				sound_alarm => alarm,
				display => display_ls_min
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for d_ms_hr
			d_ms_hr: ddrv PORT MAP(
				alarm_time => alarm_time_ms_hr,
				clk => clk,
				current_time => current_time_ms_hr,
				key_buffer => key_buffer_3,
				show_a => show_a,
				show_new_time => show_new_time,
				alarm_in => sound_alarm_test1,
				sound_alarm => alarm,
				display => display_ms_hr
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for d_ms_min
			d_ms_min: ddrv PORT MAP(
				alarm_time => alarm_time_ms_min,
				clk => clk,
				current_time => current_time_ms_min,
				key_buffer => key_buffer_1,
				show_a => show_a,
				show_new_time => show_new_time,
				sound_alarm => alarm,
				display => display_ms_min
			);
			-- End of Generated Instance Port Map
			-- Generated Instance Port Map for u_and_f
			u_and_f: and_f PORT MAP(
				y => alarm,
				clk => clk,
				reset => reset,
				out => sound_alarm,
				out_2 => sound_alarm_test1
			);
			-- End of Generated Instance Port Map


end ddrv4_struct;

--
--!End of Entity/ies
-- --------------------------------------------------------------
