-- -------------------------------------------------------------
--
-- Generated Configuration for __COMMON__
--
-- Generated
--  by:  wig
--  on:  Tue Oct 14 14:03:13 2003
--  cmd: H:\work\mix\mix_0.pl -nodelta ..\howto.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Entity Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.27 2003/09/08 15:14:24 wig Exp 
--
-- Generator: mix_0.pl Version: Revision: 1.16 , wilfried.gaensheimer@micronas.com
-- (C) 2003 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/conf


--
-- Start of Generated Configuration inst_a_e_rtl_conf / inst_a_e
--
configuration inst_a_e_rtl_conf of inst_a_e is
        for rtl

	    	-- Generated Configuration
			for inst_aa : inst_aa_e
				use configuration work.inst_aa_e_rtl_conf;
			end for;
			for inst_ab : inst_ab_e
				use configuration work.inst_ab_e_rtl_conf;
			end for;


	end for; 
end inst_a_e_rtl_conf;
--
-- End of Generated Configuration inst_a_e_rtl_conf
--

--
-- Start of Generated Configuration inst_t_e_rtl_conf / inst_t_e
--
configuration inst_t_e_rtl_conf of inst_t_e is
        for rtl

	    	-- Generated Configuration
			for inst_a : inst_a_e
				use configuration work.inst_a_e_rtl_conf;
			end for;
			for inst_b : inst_b_e
				use configuration work.inst_b_e_rtl_conf;
			end for;


	end for; 
end inst_t_e_rtl_conf;
--
-- End of Generated Configuration inst_t_e_rtl_conf
--

--
--!End of Configuration/ies
-- --------------------------------------------------------------
