-- -------------------------------------------------------------
--
--  Entity Declaration for __COMMON__
--
-- Generated
--  by:  wig
--  on:  Tue Oct 14 14:03:13 2003
--  cmd: H:\work\mix\mix_0.pl -nodelta ..\howto.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Entity Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.27 2003/09/08 15:14:24 wig Exp 
--
-- Generator: mix_0.pl Version: Revision: 1.16 , wilfried.gaensheimer@micronas.com
-- (C) 2003 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/enty

--

--
-- Start of Generated Entity inst_a_e
--
entity inst_a_e is
        -- Generics:
		-- No Generated Generics for Entity inst_a_e

    	-- Generated Port Declaration:
		port(
		-- Generated Port for Entity inst_a_e
			mfrc_p1_o	: out	std_ulogic_vector(3 downto 0);
			the_bus_part_const	: out	std_ulogic_vector(7 downto 0)
		-- End of Generated Port for Entity inst_a_e
		);
end inst_a_e;
--
-- End of Generated Entity inst_a_e
--

--
-- Start of Generated Entity inst_aa_e
--
entity inst_aa_e is
        -- Generics:
		-- No Generated Generics for Entity inst_aa_e

    	-- Generated Port Declaration:
		-- No Generated Port for Entity inst_aa_e

end inst_aa_e;
--
-- End of Generated Entity inst_aa_e
--

--
-- Start of Generated Entity inst_ab_e
--
entity inst_ab_e is
        -- Generics:
		-- No Generated Generics for Entity inst_ab_e

    	-- Generated Port Declaration:
		-- No Generated Port for Entity inst_ab_e

end inst_ab_e;
--
-- End of Generated Entity inst_ab_e
--

--
-- Start of Generated Entity inst_b_e
--
entity inst_b_e is
        -- Generics:
		-- No Generated Generics for Entity inst_b_e

    	-- Generated Port Declaration:
		port(
		-- Generated Port for Entity inst_b_e
			mfrc_p1xo_o	: in	std_ulogic_vector(1 downto 0);
			the_bus_part_const	: in	std_ulogic_vector(7 downto 0)
		-- End of Generated Port for Entity inst_b_e
		);
end inst_b_e;
--
-- End of Generated Entity inst_b_e
--

--
-- Start of Generated Entity inst_t_e
--
entity inst_t_e is
        -- Generics:
		-- No Generated Generics for Entity inst_t_e

    	-- Generated Port Declaration:
		-- No Generated Port for Entity inst_t_e

end inst_t_e;
--
-- End of Generated Entity inst_t_e
--

--
--!End of Entity/ies
-- --------------------------------------------------------------
