-- -------------------------------------------------------------
--
-- Generated Architecture Declaration for __COMMON__ of __COMMON__
--
-- Generated
--  by:  wig
--  on:  Tue Oct 14 14:03:13 2003
--  cmd: H:\work\mix\mix_0.pl -nodelta ..\howto.xls
--
-- !!! Do not edit this file! Autogenerated by MIX !!!
-- $Author$
-- $Id$
-- $Date$
-- $Log$
--
-- Based on Mix Architecture Template built into RCSfile: MixWriter.pm,v 
-- Id: MixWriter.pm,v 1.27 2003/09/08 15:14:24 wig Exp 
--
-- Generator: mix_0.pl Revision: 1.16 , wilfried.gaensheimer@micronas.com
-- (C) 2003 Micronas GmbH
--
-- --------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;

-- No project specific VHDL libraries/arch


--
--
-- Start of Generated Architecture rtl of inst_a_e
--
architecture rtl of inst_a_e is 

	-- Generated Constant Declarations


	--
	-- Components
	--

	-- Generated Components
	component inst_aa_e	-- Module AA
		-- No Generated Generics
		-- No Generated Port
	end component;
	-- ---------

	component inst_ab_e	-- Module AB
		-- No Generated Generics
		-- No Generated Port
	end component;
	-- ---------



	--
	-- Nets
	--

		--
		-- Generated Signal List
		--
		--
		-- End of Generated Signal List
		--


begin

	--
	-- Generated Concurrent Statements
	--

	-- Generated Signal Assignments


	--
	-- Generated Instances
	--

	-- Generated Instances and Port Mappings
		-- Generated Instance Port Map for inst_aa
		inst_aa: inst_aa_e	-- Module AA

		;
		-- End of Generated Instance Port Map for inst_aa

		-- Generated Instance Port Map for inst_ab
		inst_ab: inst_ab_e	-- Module AB

		;
		-- End of Generated Instance Port Map for inst_ab



end rtl;

--
-- Start of Generated Architecture rtl of inst_t_e
--
architecture rtl of inst_t_e is 

	-- Generated Constant Declarations


	--
	-- Components
	--

	-- Generated Components
	component inst_a_e	-- Module A
		-- No Generated Generics
		port (
		-- Generated Port for Entity inst_a_e
			mfrc_p1_o	: out	std_ulogic_vector(3 downto 0);
			the_bus_part_const	: out	std_ulogic_vector(7 downto 0)
		-- End of Generated Port for Entity inst_a_e
		);
	end component;
	-- ---------

	component inst_b_e	-- Module B
		-- No Generated Generics
		port (
		-- Generated Port for Entity inst_b_e
			mfrc_p1xo_o	: in	std_ulogic_vector(1 downto 0);
			the_bus_part_const	: in	std_ulogic_vector(7 downto 0)
		-- End of Generated Port for Entity inst_b_e
		);
	end component;
	-- ---------



	--
	-- Nets
	--

		--
		-- Generated Signal List
		--
			signal	mix_logic0_bus	: std_ulogic_vector(1 downto 0); 
			constant a_const_c : std_ulogic_vector(1 downto 0) := "11"; -- __I_ConvConstant: 3
			signal a_const : std_ulogic_vector(1 downto 0);
			signal	mfrc_p1	: std_ulogic_vector(3 downto 0); 
			signal	the_bus_part_const	: std_ulogic_vector(7 downto 0); 
		--
		-- End of Generated Signal List
		--


begin

	--
	-- Generated Concurrent Statements
	--

	-- Generated Signal Assignments
			mix_logic0_bus <= ( others => '0' );
			a_const <= a_const_c;


	--
	-- Generated Instances
	--

	-- Generated Instances and Port Mappings
		-- Generated Instance Port Map for inst_a
		inst_a: inst_a_e	-- Module A
		port map (
			mfrc_p1_o => mfrc_p1, -- Assign low
			mfrc_p1_o(3 downto 2)  => mix_logic0_bus, -- __W_PORT
			the_bus_part_const(0) => the_bus_part_const(0),
			the_bus_part_const(1) => the_bus_part_const(1),
			the_bus_part_const(3 downto 2)  => a_const, -- __W_PORT
			the_bus_part_const(4) => the_bus_part_const(2),
			the_bus_part_const(5) => the_bus_part_const(3),
			the_bus_part_const(6) => the_bus_part_const(4),
			the_bus_part_const(7) => the_bus_part_const(5) -- Assign Three
		);
		-- End of Generated Instance Port Map for inst_a

		-- Generated Instance Port Map for inst_b
		inst_b: inst_b_e	-- Module B
		port map (
			mfrc_p1xo_o => mfrc_p1(1 downto 0), -- Assign low
			the_bus_part_const => the_bus_part_const -- Assign Three
		);
		-- End of Generated Instance Port Map for inst_b



end rtl;

--
--!End of Architecture/s
-- --------------------------------------------------------------
