#!/bin/sh -- # -*- perl -*- -w
# TODO: Get better startup (look in FAQ ...)
eval 'exec $M_PERL -S $0 ${1+"$@"}'
if 0; # dynamic perl startup; suppress preceding line in perl

# eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}' || eval 'exec perl -S $0 $argv'
# if 0; # dynamic perl startup

#
# +-----------------------------------------------------------------------+
# |                                                                       |
# |   Copyright Micronas GmbH, Inc. 2002.                        |
# |     All Rights Reserved.                     |
# |                                                                       |
# |                                                                       |
# | THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MICRONAS GMBH |
# | The copyright notice above does not evidence any actual or intended   |
# | publication of such source code.                                      |
# |                                                                       |
# +-----------------------------------------------------------------------+

# +-----------------------------------------------------------------------+
# | Id              : $Id: mix-be.pl,v 1.2 2003/12/04 14:39:09 abauer Exp $
# | Name         : $Name:  $
# | Description  :$Descripton$
# | Parameters  : -
# | Version       : $Version$
# | Mod.Date    : $Date: 2003/12/04 14:39:09 $
# | Author        : $Author: abauer $
# | Phone         : $Phone$
# | Fax             : $Fax$
# | Email         : $Email$
# |
# | Copyright (c)2002 Micronas GmbH. All Rights Reserved.
# | MIX proprietary and confidential information.
# |
# +-----------------------------------------------------------------------+

# +-----------------------------------------------------------------------+
# |
# | Changes:
# | $Log: mix-be.pl,v $
# | Revision 1.2  2003/12/04 14:39:09  abauer
# | *** empty log message ***
# |
# | Revision 1.1.1.1  2003/02/03 12:56:44  wig
# | Importing pilot release of MIX tools
# |
# |
# +-----------------------------------------------------------------------+

# --------------------------------------------------------------------------

#******************************************************************************
# Other required packages
#******************************************************************************

use strict;
use Cwd;
use File::Basename;
use Getopt::Long qw(GetOptions);
use Pod::Text;
# use diagnostics; # -> will be set by -debug option
# use English;       # -> will not need this, just consumes performance

# These packages need to be installed, too
use lib 'h:\work\x2v\lib\perl'; ##TODO: Rewrite that to a generic place ....
use Log::Agent;
use Log::Agent::Priorities qw(:LEVELS);

use Micronas::MixUtils;
use Micronas::MixParser;

##############################################################################
# Prototypes (generated by "grep ^sub PROG | sed -e 's/$/;/'")

#t.b.d...

#******************************************************************************
# Global Variables
#******************************************************************************

$::VERSION="/mix-be/0.1";

# %EH comes from Mic::MixUtils ; All the configuration E-nvironment will be there

use vars qw($pgm $base);
($pgm=$0) =~s;^.*(/|\\);;g;
($base=$0) =~s;^(.*)[/\\]\w+[/\\][\w\.]+$;$1;g;

my $dir;
($^O=~/Win32/) ? ($dir=getcwd())=~s,/,\\,g : ($dir=getcwd());

#
# Step 0: Init $0
#
mix_init();               # Presets ....

#
# Read intermediate dump file name
#
mix_getopt_header(qw(
    int=s
    ));

mix_load_db("in"); # Load data dumped to intermediate file ...

#
# Backend processing
#
